
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action addAction;
	private global::Gtk.Action editAction;
	private global::Gtk.Action deleteAction;
	private global::Gtk.Action refreshAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.Notebook notebook3;
	private global::Gtk.ScrolledWindow scrolledwindow2;
	private global::Gtk.TreeView treeArticulos;
	private global::Gtk.Label LArticulo;
	private global::Gtk.ScrolledWindow scrolledwindow1;
	private global::Gtk.TreeView treeCategorias;
	private global::Gtk.Label LCategoria;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
		w1.Add (this.addAction, null);
		this.editAction = new global::Gtk.Action ("editAction", null, null, "gtk-edit");
		w1.Add (this.editAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", null, null, "gtk-remove");
		w1.Add (this.deleteAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='refreshAction' action='refreshAction'/><toolitem name='addAction' action='addAction'/><toolitem name='editAction' action='editAction'/><toolitem name='deleteAction' action='deleteAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook3 = new global::Gtk.Notebook ();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 1;
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.treeArticulos = new global::Gtk.TreeView ();
		this.treeArticulos.CanFocus = true;
		this.treeArticulos.Name = "treeArticulos";
		this.scrolledwindow2.Add (this.treeArticulos);
		this.notebook3.Add (this.scrolledwindow2);
		// Notebook tab
		this.LArticulo = new global::Gtk.Label ();
		this.LArticulo.Name = "LArticulo";
		this.LArticulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Artículos");
		this.notebook3.SetTabLabel (this.scrolledwindow2, this.LArticulo);
		this.LArticulo.ShowAll ();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.treeCategorias = new global::Gtk.TreeView ();
		this.treeCategorias.CanFocus = true;
		this.treeCategorias.Name = "treeCategorias";
		this.scrolledwindow1.Add (this.treeCategorias);
		this.notebook3.Add (this.scrolledwindow1);
		global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3 [this.scrolledwindow1]));
		w6.Position = 1;
		// Notebook tab
		this.LCategoria = new global::Gtk.Label ();
		this.LCategoria.Name = "LCategoria";
		this.LCategoria.LabelProp = global::Mono.Unix.Catalog.GetString ("Categorias");
		this.notebook3.SetTabLabel (this.scrolledwindow1, this.LCategoria);
		this.LCategoria.ShowAll ();
		this.vbox1.Add (this.notebook3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook3]));
		w7.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.deleteAction.Activated += new global::System.EventHandler (this.OnDeleteActionActivated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
	}
}
